// const ITEMS = [
//     {
//         id: 1,
//         name: 'Item 1ICABLE Boys Plain T-Shirts Cotton Blend',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'https://m.media-amazon.com/images/I/41fXiyaDcKL._SX679_.jpg',
//         otherImages: ['http://surl.li/ivqpor', 'imges/productimg/f1.jpg', 'imges/productimg/f2.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 2,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 3,
//         name: 'Item 3',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 4,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 5,
//         name: 'Item 5',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 2,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 6,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 7,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 8,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 9,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 10,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 11,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 5,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
//     {
//         id: 12,
//         name: 'Item 1',
//         brand: 'adidas',
//         price: 78,
//         imageUrl: 'imges/productimg/f1.jpg',
//         otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
//         size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
//         description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.`,
//         rating: 2,
//         stockQty: 10,
//         category: 'T-Shirt',
//     },
// ]
const ITEMS = [
    {
        id: 1,
        name: 'ICABLE Boys Plain T-Shirts Cotton Blend',
        brand: 'Sporty & Rich',
        price: 350,
        imageUrl: 'https://m.media-amazon.com/images/I/41fXiyaDcKL.SX679.jpg',
        otherImages: ['http://surl.li/ivqpor', 'https://shorturl.at/2siU9', 'https://shorturl.at/cqoIi', 'https://shorturl.at/zkJwy'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 4,
        stockQty: 9,
        category: 'T-Shirt',
    },
    {
        id: 2,
        name: 'Item 2',
        brand: 'Rare Shirts',
        price: 600,
        imageUrl: 'https://shorturl.at/GloRJ',
        otherImages: ['https://shorturl.at/jAmhx', 'https://shorturl.at/d84t3', 'https://shorturl.at/8MlGn', 'https://shorturl.at/V8grA'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 4,
        stockQty: 6,
        category: 'Printed-Shirt',
    },
    {
        id: 3,
        name: 'Item 3',
        brand: 'Adidas',
        price: 7800,
        imageUrl: 'https://shorturl.at/X98oR',
        otherImages: ['https://shorturl.at/xxRiT', 'https://rb.gy/jprtz0', 'https://rb.gy/xippyl', 'https://rb.gy/atxazd'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 3,
        stockQty: 12,
        category: 'Shoes',
    },
    {
        id: 4,
        name: 'Item 4',
        brand: 'Armani',
        price: 78,
        imageUrl: 'https://rb.gy/md1zgy',
        otherImages: ['https://rb.gy/1sd19z', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 4,
        stockQty: 10,
        category: 'Jeans',
    },
    {
        id: 5,
        name: 'Item 5',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 2,
        stockQty: 10,
        category: 'T-Shirt',
    },
    {
        id: 6,
        name: 'Item 1',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 5,
        stockQty: 10,
        category: 'T-Shirt',
    },
    {
        id: 7,
        name: 'Item 1',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 5,
        stockQty: 10,
        category: 'T-Shirt',
    },
    {
        id: 8,
        name: 'Item 1',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 5,
        stockQty: 10,
        category: 'T-Shirt',
    },
    {
        id: 9,
        name: 'Item 1',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 5,
        stockQty: 10,
        category: 'T-Shirt',
    },
    {
        id: 10,
        name: 'Item 1',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 5,
        stockQty: 10,
        category: 'T-Shirt',
    },
    {
        id: 11,
        name: 'Item 1',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 5,
        stockQty: 10,
        category: 'T-Shirt',
    },
    {
        id: 12,
        name: 'Item 1',
        brand: 'adidas',
        price: 78,
        imageUrl: 'imges/productimg/f1.jpg',
        otherImages: ['imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg', 'imges/productimg/f1.jpg'],
        size: ['LG', 'XL', 'XXL', 'MD', 'SM'],
        description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Earum laboriosam accusamus alias atque autem tempore vel voluptatibus odio illum dignissimos beatae, incidunt optio eius cupiditate quos blanditiis rerum porro est? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi commodi, tenetur, consequatur maxime numquam earum laudantium fuga illum quisquam praesentium cupiditate ab id suscipit, ratione quam voluptatibus officia reiciendis! Similique.',
        rating: 2,
        stockQty: 10,
        category: 'T-Shirt',
    },
]

window.localStorage.setItem('items', JSON.stringify(ITEMS))

const fetchedItems = JSON.parse(window.localStorage.getItem('items'))

const productSection = document.getElementById('products-section');

fetchedItems.forEach((item) => {
    const starsHTML = Array(item.rating).fill('<i class="fas fa-star"></i>').join('');

    const productHTML = `
        <div class="pro" data-id="${item.id}">
            <img src="${item.imageUrl}" alt="">
            <div class="des">
                <span>${item.brand}</span>
                <h5>${item.name}</h5>
                <div class="star">
                    ${starsHTML}
                </div>
                <h4>$${item.price}</h4>
            </div>
            <a href="#"><i class="fa fa-shopping-cart" id="cart"></i></a>
        </div>
    `;
    productSection.innerHTML += productHTML;
});

document.querySelectorAll('.pro').forEach(product => {
    product.addEventListener('click', function () {
        const productId = this.getAttribute('data-id');
        window.location.href = `sproduct.html?id=${productId}`;
    });
});